### Data Invertory  資料盤點

In [119]:
import pandas as pd
from pathlib import Path 
import os
import numpy as np
pd.set_option("display.max_colwidth", None)      # 不截斷欄位內容
pd.set_option("display.max_rows", 200)           # 想看更多 row 可調
pd.set_option("display.max_columns", 50)

In [64]:
PROJECT_ROOT = Path("/Users/kaiping/Desktop/olist_project")  # 定義專案根目錄(絕對路徑)
RAW = PROJECT_ROOT / "data" / "raw" # 組出raw資料夾路徑

df_translation = pd.read_csv(RAW / "product_category_name_translation.csv")
df_sellers     = pd.read_csv(RAW / "olist_sellers_dataset.csv")
df_products    = pd.read_csv(RAW / "olist_products_dataset.csv")
df_orders      = pd.read_csv(RAW / "olist_orders_dataset.csv")
df_order_reviews  = pd.read_csv(RAW / "olist_order_reviews_dataset.csv")
df_order_payments = pd.read_csv(RAW / "olist_order_payments_dataset.csv")
df_order_items    = pd.read_csv(RAW / "olist_order_items_dataset.csv")
df_geolocation    = pd.read_csv(RAW / "olist_geolocation_dataset.csv")
df_customers      = pd.read_csv(RAW / "olist_customers_dataset.csv")

In [65]:
df_translation = pd.read_csv(RAW / "product_category_name_translation.csv")
df_sellers     = pd.read_csv(RAW / "olist_sellers_dataset.csv")
df_products    = pd.read_csv(RAW / "olist_products_dataset.csv")
df_orders      = pd.read_csv(RAW / "olist_orders_dataset.csv")
df_order_reviews  = pd.read_csv(RAW / "olist_order_reviews_dataset.csv")
df_order_payments = pd.read_csv(RAW / "olist_order_payments_dataset.csv")
df_order_items    = pd.read_csv(RAW / "olist_order_items_dataset.csv")
df_geolocation    = pd.read_csv(RAW / "olist_geolocation_dataset.csv")
df_customers      = pd.read_csv(RAW / "olist_customers_dataset.csv")

In [66]:
tables = {
    "translation":df_translation,
    "sellers":df_sellers,
    "product":df_products,
    "orders":df_orders,
    "order_review":df_order_reviews,
    "order_payment":df_order_payments,
    "order_items":df_order_items,
    "geolocation":df_geolocation,
    "customer":df_customers}

In [67]:
inventory = []

for name, df in tables.items():
    inventory.append({
        "table_name": name,
        "row_count": df.shape[0], # 取第一維即是row數
        "column_count": df.shape[1] # 第二維
    })

df_inventory = pd.DataFrame(inventory)
df_inventory

      table_name  row_count  column_count
0    translation         71             2
1        sellers       3095             4
2        product      32951             9
3         orders      99441             8
4   order_review      99224             7
5  order_payment     103886             5
6    order_items     112650             7
7    geolocation    1000163             5
8       customer      99441             5

### Column inventory 欄位理解

In [72]:
def build_column_inventory(tables: dict, sample_n: int = 3, unique_threshold: int = 30) -> pd.DataFrame:
    rows = []

    for table_name, df in tables.items():
        row_count = df.shape[0]

        for col in df.columns:
            s = df[col]
            null_count = int(s.isna().sum())
            null_rate = (null_count / row_count) if row_count > 0 else 0.0
            n_unique = int(s.nunique(dropna=True))

            # 取前 sample_n 個非缺失樣本值
            sample_values = s.dropna().head(sample_n).tolist()

            # 若 n_unique 小於門檻，列出 unique 清單（排除缺失）
            unique_list = None
            if n_unique < unique_threshold:
                unique_list = s.dropna().unique().tolist()

            rows.append({
                "table_name": table_name,
                "column_name": col,
                "dtype": str(s.dtype),
                "row_count": row_count,
                "null_count": null_count,
                "null_rate": round(null_rate, 6),
                "n_unique": n_unique,
                "sample_values": sample_values,
                "unique_list": unique_list
            })

    column_inventory = (
        pd.DataFrame(rows)
        .sort_values(["table_name", "column_name"])
        .reset_index(drop=True)
    )
    return column_inventory

def add_business_meaning(
    column_inventory: pd.DataFrame,
    table_name: str,
    column_name: str,
    meaning: str
) -> pd.DataFrame:
    """
    在 column_inventory 中，為指定的 table + column 填入「欄位商業意義」
    若欄位不存在，會自動在第 3 欄（index=2）新增
    """

    # 若尚未有「欄位商業意義」欄位，先建立（放在第 3 欄）
    if "欄位商業意義" not in column_inventory.columns:
        column_inventory.insert(loc=2, column="欄位商業意義", value="")

    # 指定要填寫的 row
    mask = (
        (column_inventory["table_name"] == table_name) &
        (column_inventory["column_name"] == column_name)
    )

    # 寫入商業意義
    column_inventory.loc[mask, "欄位商業意義"] = meaning

    return column_inventory

In [157]:
column_inventory = build_column_inventory(
    tables=tables,
    sample_n=3,            # 每個欄位抓前 3 個非缺失樣本
    unique_threshold=30    # 唯一值少於 30 才列 unique_list
)

column_inventory.head(100)

,table_name,column_name,dtype,row_count,null_count,null_rate,n_unique,sample_values,unique_list
0,customer,customer_city,object,99441,0,0.000000,4119,"[franca, sao bernardo do campo, sao paulo]",None
1,customer,customer_id,object,99441,0,0.000000,99441,"[06b8999e2fba1a1fbc88172c00ba8bc7, 18955e83d337fd6b2def6b18a428ac77, 4e7b3e00288586ebd08712fdd0374a03]",None
2,customer,customer_state,object,99441,0,0.000000,27,"[SP, SP, SP]","[SP, SC, MG, PR, RJ, RS, PA, GO, ES, BA, MA, MS, CE, DF, RN, PE, MT, AM, AP, AL, RO, PB, TO, PI, AC, SE, RR]"
3,customer,customer_unique_id,object,99441,0,0.000000,96096,"[861eff4711a542e4b93843c6dd7febb0, 290c77bc529b7ac935b93aa66c333dc3, 060e732b5b29e8181a18229c7b0b2b5e]",None
4,customer,customer_zip_code_prefix,int64,99441,0,0.000000,14994,"[14409, 9790, 1151]",None
5,geolocation,geolocation_city,object,1000163,0,0.000000,8011,"[sao paulo, sao paulo, sao paulo]",None
6,geolocation,geolocation_lat,float64,1000163,0,0.000000,716685,"[-23.54562128, -23.54608113, -23.54612897]",None
7,geolocation,geolocation_lng,float64,1000163,0,0.000000,717097,"[-46.63929205, -46.6448203, -46.64295148]",None
8,geolocation,geolocation_state,object,1000163,0,0.000000,27,"[SP, SP, SP]","[SP, RN, AC, RJ, ES, MG, BA, SE, PE, AL, PB, CE, PI, MA, PA, AP, AM, RR, DF, GO, RO, TO, MT, MS, RS, PR, SC]"
9,geolocation,geolocation_zip_code_prefix,int64,1000163,0,0.000000,19015,"[1037, 1046, 1046]",None
10,order_items,freight_value,float64,112650,0,0.000000,6999,"[13.29, 19.93, 17.87]",None
11,order_items,order_id,object,112650,0,0.000000,98666,"[00010242fe8c5a6d1ba2dd792cb16214, 00018f77f2f0320c557190d7a144bdd3, 000229ec398224ef6ca0657da4fc703e]",None
12,order_items,order_item_id,int64,112650,0,0.000000,21,"[1, 1, 1]","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]"
13,order_items,price,float64,112650,0,0.000000,5968,"[58.9, 239.9, 199.0]",None
14,order_items,product_id,object,112650,0,0.000000,32951,"[4244733e06e7ecb4970a6e2683c13e61, e5f2d52b802189ee658865ca93d83a8f, c777355d18b72b67abbeef9df44fd0fd]",None
15,order_items,seller_id,object,112650,0,0.000000,3095,"[48436dade18ac8b2bce089ec2a041202, dd7ddc04e1b6c2c614352b383efe2d36, 5b51032eddd242adc84c38acab88f23d]",None
16,order_items,shipping_limit_date,object,112650,0,0.000000,54615,"[2017/9/19 9:45, 2017/5/3 11:05, 2018/1/18 14:48]",None
17,order_payment,order_id,object,103886,0,0.000000,99440,"[b81ef226f3fe1789b1e8b2acac839d17, a9810da82917af2d9aefd1278f1dcfa0, 25e8ea4e93396b6fa0d3dd708e76c1bd]",None
18,order_payment,payment_installments,int64,103886,0,0.000000,24,"[8, 1, 1]","[8, 1, 2, 3, 6, 5, 4, 10, 7, 12, 9, 13, 15, 24, 11, 18, 14, 20, 21, 17, 22, 0, 16, 23]"
19,order_payment,payment_sequential,int64,103886,0,0.000000,29,"[1, 1, 1]","[1, 2, 4, 5, 3, 8, 6, 7, 10, 11, 17, 19, 27, 12, 9, 15, 13, 14, 16, 25, 22, 26, 29, 28, 18, 21, 24, 23, 20]"
20,order_payment,payment_type,object,103886,0,0.000000,5,"[credit_card, credit_card, credit_card]","[credit_card, boleto, voucher, debit_card, not_defined]"
21,order_payment,payment_value,float64,103886,0,0.000000,29077,"[99.33, 24.39, 65.71]",None
22,order_review,order_id,object,99224,0,0.000000,98673,"[73fc7af87114b39712e6da79b0a377eb, a548910a1c6147796b98fdf73dbeba33, f9e4b658b201a9f2ecdecbb34bed034b]",None
23,order_review,review_answer_timestamp,object,99224,0,0.000000,88867,"[2018/1/18 21:46, 2018/3/11 3:05, 2018/2/18 14:36]",None
24,order_review,review_comment_message,object,99224,58265,0.587207,36135,"[Recebi bem antes do prazo estipulado., Parabéns lojas lannister adorei comprar pela Internet seguro e prático Parabéns a todos feliz Páscoa, aparelho eficiente. no site a marca do aparelho esta impresso como 3desinfector e ao chegar esta com outro nome...atualizar com a marca correta uma vez que é o mesmo aparelho]",None
25,order_review,review_comment_title,object,99224,87663,0.883486,4503,"[recomendo, Super recomendo, Não chegou meu produto ]",None
26,order_review,review_creation_date,object,99224,0,0.000000,636,"[2018/1/18 0:00, 2018/3/10 0:00, 2018/2/17 0:00]",None
27,order_review,review_id,object,99224,0,0.000000,98410,"[7bc2406110b926393aa56f80a40eba40, 80e641a11e56f04c1ad469d5645fdfde, 228ce5500dc1d8e020d8d1322874b6f0]",None
28,order_review,review_score,int64,99224,0,0.000000,5,"[4, 5, 5]","[4, 5, 1, 3, 2]"
29,orders,customer_id,object,99441,0,0.000000,99441,"[9ef432eb6251297304e76186b10a928d, b0830fb4747a6c6d20dea0b8c802d7ef, 41ce2a54c0b03bf3443c3d931a367089]",None
30,orders,order_approved_at,object,99441,160,0.001609,50462,"[2017/10/2 11:07, 2018/7/26 3:24, 2018/8/8 8:55]",None
31,orders,order_delivered_carrier_date,object,99441,1783,0.017930,61544,"[2017/10/4 19:55, 2018/7/26 14:31, 2018/8/8 13:50]",None
32,orders,order_delivered_customer_date,object,99441,2965,0.029817,75649,"[2017/10/10 21:25, 2018/8/7 15:27, 2018/8/17 18:06]",None
33,orders,order_estimated_delivery_date,object,99441,0,0.000000,459,"[2017/10/18 0:00, 2018/8/13 0:00, 2018/9/4 0:00]",None
34,orders,order_id,object,99441,0,0.000000,99441,"[e481f51cbdc54678b7cc49136f2d6af7, 53cdb2fc8bc7dce0b6741e2150273451, 47770eb9100c2d0c44946d9cf07ec65d]",None
35,orders,order_purchase_timestamp,object,99441,0,0.000000,88789,"[2017/10/2 10:56, 2018/7/24 20:41, 2018/8/8 8:38]",None
36,orders,order_status,object,99441,0,0.000000,8,"[delivered, delivered, delivered]","[delivered, invoiced, shipped, processing, unavailable, canceled, created, approved]"
37,product,product_category_name,object,32951,610,0.018512,73,"[perfumaria, artes, esporte_lazer]",None
38,product,product_description_lenght,float64,32951,610,0.018512,2960,"[287.0, 276.0, 250.0]",None
39,product,product_height_cm,float64,32951,2,0.000061,102,"[10.0, 18.0, 9.0]",None
40,product,product_id,object,32951,0,0.000000,32951,"[1e9e8ef04dbcff4541ed26657ea517e5, 3aa071139cb16b67ca9e5dea641aaa2f, 96bd76ec8810374ed1b65e291975717f]",None
41,product,product_length_cm,float64,32951,2,0.000061,99,"[16.0, 30.0, 18.0]",None
42,product,product_name_lenght,float64,32951,610,0.018512,66,"[40.0, 44.0, 46.0]",None
43,product,product_photos_qty,float64,32951,610,0.018512,19,"[1.0, 1.0, 1.0]","[1.0, 4.0, 2.0, 3.0, 5.0, 9.0, 6.0, 7.0, 12.0, 10.0, 11.0, 17.0, 8.0, 15.0, 13.0, 14.0, 20.0, 18.0, 19.0]"
44,product,product_weight_g,float64,32951,2,0.000061,2204,"[225.0, 1000.0, 154.0]",None
45,product,product_width_cm,float64,32951,2,0.000061,95,"[14.0, 20.0, 15.0]",None
46,sellers,seller_city,object,3095,0,0.000000,611,"[campinas, mogi guacu, rio de janeiro]",None
47,sellers,seller_id,object,3095,0,0.000000,3095,"[3442f8959a84dea7ee197c632cb2df15, d1b65fc7debc3361ea86b5f14c68d2e2, ce3ad9de960102d0677a81f5d0bb7b2d]",None
48,sellers,seller_state,object,3095,0,0.000000,23,"[SP, SP, RJ]","[SP, RJ, PE, PR, GO, SC, BA, DF, RS, MG, RN, MT, CE, PB, AC, ES, RO, PI, MS, SE, MA, AM, PA]"
49,sellers,seller_zip_code_prefix,int64,3095,0,0.000000,2246,"[13023, 13844, 20031]",None
50,translation,product_category_name,object,71,0,0.000000,71,"[beleza_saude, informatica_acessorios, automotivo]",None
51,translation,product_category_name_english,object,71,0,0.000000,71,"[health_beauty, computers_accessories, auto]",None

### 使用excel進行欄位商業意義分析

In [86]:

target_dir = "/Users/kaiping/Desktop/olist_project/notebooks/data_understanding"
os.chdir(target_dir)
output_path = Path("column_inventory.csv")
if not output_path.exists():
    column_inventory.to_csv(output_path, index=False, encoding="utf-8-sig")
    print(f"已儲存：{output_path}（位於 {os.getcwd()}）")
else:
    print(f"已存在，未覆蓋：{output_path}（位於 {os.getcwd()}）")

已存在，未覆蓋：column_inventory.csv（位於 /Users/kaiping/Desktop/olist_project/notebooks/data_understanding）

在進行欄位理解的時候，發現顧客表有兩個欄位 customer_id 和 customer_unique_id，我要驗證customer_id和  
order_id 是否數量一樣

訂單表 order_id (PK) 有99441筆
顧客表 customer_id(PK) 有99441筆
可以驗證只要客戶下單後就會產生一筆customer_id

In [ ]:
為什麼郵遞區號有四碼的還有五碼的？

In [ ]:
df_geolocation["geolocation_zip_code_prefix"].astype(str).str.len().value_counts()
# 讀取csv檔案時候開頭是0會被取消，巴西郵遞區號有0開頭的，後續資料處理要補0

訂單明細表的運費在同一筆訂單裡面理所應當要相同，需要驗證

In [97]:
check = (
    df_order_items
    .groupby("order_id")["freight_value"]
    .nunique()
    .reset_index(name="freight_value_cnt")
)

abnormal_orders = check[check["freight_value_cnt"] > 1]
abnormal_orders

                               order_id  freight_value_cnt
73     002f98c0f7efd42638ed6100ca699b42                  2
134    005d9a5423d47281ac463a968b3936fb                  2
198    00946f674d880be1f188abc10ad7cf46                  2
208    0097f0545a302aafa32782f1734ff71c                  2
268    00bcee890eba57a9767c7b5ca12d3a1b                  2
...                                 ...                ...
98555  ffb18bf111fa70edf316eb0390427986                  2
98563  ffb8f7de8940249a3221252818937ecb                  3
98564  ffb9a9cd00c74c11c24aa30b3d78e03b                  3
98575  ffc16cecff8dc037f60458f28d1c1ba5                  2
98596  ffd543c2b60842e148a86870dc60e212                  2

[2030 rows x 2 columns]

In [107]:
abnormal_orders["freight_value_cnt"].value_counts().sort_index()

# 訂單明細表中有兩種不同運費的有2000多筆
# 一筆訂單有大於1種不同的運費的資料，有4種，分別是 2,3,4,5

freight_value_cnt
2    1881
3     138
4      10
5       1
Name: count, dtype: int64

為何訂單明細表同一筆訂單會有多種不一樣的運費？  
推測是同一筆訂單買了多個seller的商品，每個seller的商品運費都不一樣，每個seller各自計算運費

In [108]:
# 每筆訂單：運費有幾種、賣家有幾個
order_level = (
    df_order_items
    .groupby("order_id")
    .agg(
        freight_cnt=("freight_value", "nunique"),
        seller_cnt=("seller_id", "nunique"),
        item_cnt=("order_item_id", "count")
    )
    .reset_index()
)

# 只看運費>1的訂單，有多少是 seller_cnt>1
pd.crosstab(order_level["freight_cnt"] > 1, order_level["seller_cnt"] > 1, margins=True)

seller_cnt   False  True    All
freight_cnt
False        96393   243  96636
True           995  1035   2030
All          97388  1278  98666

In [113]:
# payment_installments 、 payment_sequential 代表啥意義？

df_order_payments.head(20)
# payment_installments 分期期數
# sequential 代表付款次序從1開始遞增

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
5,298fcdf1f73eb413e4d26d01b25bc1cd,1,credit_card,2,96.12
6,771ee386b001f06208a7419e4fc1bbd7,1,credit_card,1,81.16
7,3d7239c394a212faae122962df514ac7,1,credit_card,3,51.84
8,1f78449c87a54faf9e96e88ba1491fa9,1,credit_card,6,341.09
9,0573b5e23cbd798006520e1d5b4c6714,1,boleto,1,51.95
10,d88e0d5fa41661ce03cf6cf336527646,1,credit_card,8,188.73
11,2480f727e869fdeb397244a21b721b67,1,credit_card,1,141.90
12,616105c9352a9668c38303ad44e056cd,1,credit_card,1,75.78
13,cf95215a722f3ebf29e6bbab87a29e61,1,credit_card,5,102.66
14,769214176682788a92801d8907fa1b40,1,credit_card,4,105.28
15,12e5cfe0e4716b59afb0e0f4a3bd6570,1,credit_card,10,157.45
16,61059985a6fc0ad64e95d9944caacdad,1,credit_card,1,132.04
17,79da3f5fe31ad1e454f06f95dc032ad5,1,credit_card,1,98.94
18,8ac09207f415d55acff302df7d6a895c,1,credit_card,4,244.15
19,b2349a3f20dfbeef62e7b31baa22f84b,1,credit_card,3,136.71

In [121]:
print(f"付款次序:{np.sort(df_order_payments['payment_sequential'].unique())}\n")
print(f"分期期數:{np.sort(df_order_payments['payment_installments'].unique())}")

付款次序:[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]

分期期數:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 20 21 22 23 24]

為什麼付款次序最大29 ， 分期期數最大只有24?  
思考的結果是客人付款期數大於分期期數，超過預期期數  
或者是付款可能沒有成立

In [122]:
df_order_payments["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [128]:
print(f"共有{df_order_reviews['review_id'].count()}筆評論")

共有99224筆評論

In [146]:
print(df_orders["order_id"].nunique())
print(df_orders["customer_id"].nunique())

99441
99441

In [147]:
print(df_customers["customer_id"].nunique())

99441

訂單表的顧客id跟fk order_id數量相同，思考得出客人每下一筆訂單就會產生一個customer_id並且記錄客人個人資料

In [149]:
print(df_orders["order_status"].value_counts())

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [156]:
df_products["product_photos_qty"].dropna().astype(int).sort_values().unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 17, 18,
       19, 20])

In [158]:
column_dictionary = pd.read_csv("column_inventory.csv")
column_dictionary

,table_name,column_name,business meaning,dtype,row_count,null_count,null_rate,n_unique,sample_values,unique_list
0,customer,customer_city,顧客所在地(市),object,99441,0,0.000000,4119,"['franca', 'sao bernardo do campo', 'sao paulo']",NaN
1,customer,customer_id,顧客下單快照(PK),object,99441,0,0.000000,99441,"['06b8999e2fba1a1fbc88172c00ba8bc7', '18955e83d337fd6b2def6b18a428ac77', '4e7b3e00288586ebd08712fdd0374a03']",NaN
2,customer,customer_state,顧客所在地(州)用兩碼代碼表示,object,99441,0,0.000000,27,"['SP', 'SP', 'SP']","['SP', 'SC', 'MG', 'PR', 'RJ', 'RS', 'PA', 'GO', 'ES', 'BA', 'MA', 'MS', 'CE', 'DF', 'RN', 'PE', 'MT', 'AM', 'AP', 'AL', 'RO', 'PB', 'TO', 'PI', 'AC', 'SE', 'RR']"
3,customer,customer_unique_id,平台推算的同一個真人，同一個人只能有一個代號,object,99441,0,0.000000,96096,"['861eff4711a542e4b93843c6dd7febb0', '290c77bc529b7ac935b93aa66c333dc3', '060e732b5b29e8181a18229c7b0b2b5e']",NaN
4,customer,customer_zip_code_prefix,巴西郵遞區號前五碼，通常代表很細的地理區域，有14000個唯一值，如果顯示四碼代表資料開頭是0 (excel讀int64欄位把0取消),int64,99441,0,0.000000,14994,"[14409, 9790, 1151]",NaN
5,geolocation,geolocation_city,巴西城市名稱有8000多唯一值,object,1000163,0,0.000000,8011,"['sao paulo', 'sao paulo', 'sao paulo']",NaN
6,geolocation,geolocation_lat,郵遞區號所對應的緯度(度),float64,1000163,0,0.000000,716685,"[-23.54562128, -23.54608113, -23.54612897]",NaN
7,geolocation,geolocation_lng,郵遞區號所對應的經度(度),float64,1000163,0,0.000000,717097,"[-46.63929205, -46.6448203, -46.64295148]",NaN
8,geolocation,geolocation_state,郵遞曲號所屬州 (兩碼代碼),object,1000163,0,0.000000,27,"['SP', 'SP', 'SP']","['SP', 'RN', 'AC', 'RJ', 'ES', 'MG', 'BA', 'SE', 'PE', 'AL', 'PB', 'CE', 'PI', 'MA', 'PA', 'AP', 'AM', 'RR', 'DF', 'GO', 'RO', 'TO', 'MT', 'MS', 'RS', 'PR', 'SC']"
9,geolocation,geolocation_zip_code_prefix,巴西郵遞區號前五碼，有19000唯一值，如果顯示四碼代表資料開頭是0 (excel讀int64欄位把0取消),int64,1000163,0,0.000000,19015,"[1037, 1046, 1046]",NaN
10,order_items,freight_value,訂單明細表中的freight_value運費，在同一筆訂單的情況下有多種不同的運費不同的商品，推測是同一筆訂單可以包含很多賣家，每個賣家分別計算運費,float64,112650,0,0.000000,6999,"[13.29, 19.93, 17.87]",NaN
11,order_items,order_id,訂單明細表ID(PK),object,112650,0,0.000000,98666,"['00010242fe8c5a6d1ba2dd792cb16214', '00018f77f2f0320c557190d7a144bdd3', '000229ec398224ef6ca0657da4fc703e']",NaN
12,order_items,order_item_id,同一筆訂單中的第幾筆商品，範圍有1~21,int64,112650,0,0.000000,21,"[1, 1, 1]","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]"
13,order_items,price,訂單明細表中該商品的成交價格(不包含運費、其他商品),float64,112650,0,0.000000,5968,"[58.9, 239.9, 199.0]",NaN
14,order_items,product_id,對應商品id (FK關聯到商品表),object,112650,0,0.000000,32951,"['4244733e06e7ecb4970a6e2683c13e61', 'e5f2d52b802189ee658865ca93d83a8f', 'c777355d18b72b67abbeef9df44fd0fd']",NaN
15,order_items,seller_id,對應賣家id (FK關聯到賣家表),object,112650,0,0.000000,3095,"['48436dade18ac8b2bce089ec2a041202', 'dd7ddc04e1b6c2c614352b383efe2d36', '5b51032eddd242adc84c38acab88f23d']",NaN
16,order_items,shipping_limit_date,賣家最晚出貨期限(年月日時間),object,112650,0,0.000000,54615,"['2017/9/19 9:45', '2017/5/3 11:05', '2018/1/18 14:48']",NaN
17,order_payment,order_id,同一筆訂單中的第幾次付款紀錄(有1~24)代表可以分期付款,object,103886,0,0.000000,99440,"['b81ef226f3fe1789b1e8b2acac839d17', 'a9810da82917af2d9aefd1278f1dcfa0', '25e8ea4e93396b6fa0d3dd708e76c1bd']",NaN
18,order_payment,payment_installments,訂單分期期數(1~24),int64,103886,0,0.000000,24,"[8, 1, 1]","[8, 1, 2, 3, 6, 5, 4, 10, 7, 12, 9, 13, 15, 24, 11, 18, 14, 20, 21, 17, 22, 0, 16, 23]"
19,order_payment,payment_sequential,付款事件的順序(從1遞增到29),int64,103886,0,0.000000,29,"[1, 1, 1]","[1, 2, 4, 5, 3, 8, 6, 7, 10, 11, 17, 19, 27, 12, 9, 15, 13, 14, 16, 25, 22, 26, 29, 28, 18, 21, 24, 23, 20]"
20,order_payment,payment_type,"付款方式共有五種['credit_card', 'boleto', 'voucher', 'debit_card', 'not_defined']",object,103886,0,0.000000,5,"['credit_card', 'credit_card', 'credit_card']","['credit_card', 'boleto', 'voucher', 'debit_card', 'not_defined']"
21,order_payment,payment_value,付款金額,float64,103886,0,0.000000,29077,"[99.33, 24.39, 65.71]",NaN
22,order_review,order_id,訂單編號(FK關聯到訂單表)一筆訂單可以有很多評論,object,99224,0,0.000000,98673,"['73fc7af87114b39712e6da79b0a377eb', 'a548910a1c6147796b98fdf73dbeba33', 'f9e4b658b201a9f2ecdecbb34bed034b']",NaN
23,order_review,review_answer_timestamp,評論回覆(年月日時間),object,99224,0,0.000000,88867,"['2018/1/18 21:46', '2018/3/11 3:05', '2018/2/18 14:36']",NaN
24,order_review,review_comment_message,評論內容,object,99224,58265,0.587207,36135,"['Recebi bem antes do prazo estipulado.', 'Parabéns lojas lannister adorei comprar pela Internet seguro e prático Parabéns a todos feliz Páscoa', 'aparelho eficiente. no site a marca do aparelho esta impresso como 3desinfector e ao chegar esta com outro nome...atualizar com a marca correta uma vez que é o mesmo aparelho']",NaN
25,order_review,review_comment_title,評論標題,object,99224,87663,0.883486,4503,"['recomendo', 'Super recomendo', 'Não chegou meu produto ']",NaN
26,order_review,review_creation_date,評論建立時間(年月日時間),object,99224,0,0.000000,636,"['2018/1/18 0:00', '2018/3/10 0:00', '2018/2/17 0:00']",NaN
27,order_review,review_id,評論ID(PK),object,99224,0,0.000000,98410,"['7bc2406110b926393aa56f80a40eba40', '80e641a11e56f04c1ad469d5645fdfde', '228ce5500dc1d8e020d8d1322874b6f0']",NaN
28,order_review,review_score,評論分數1~5,int64,99224,0,0.000000,5,"[4, 5, 5]","[4, 5, 1, 3, 2]"
29,orders,customer_id,顧客ID(FK),object,99441,0,0.000000,99441,"['9ef432eb6251297304e76186b10a928d', 'b0830fb4747a6c6d20dea0b8c802d7ef', '41ce2a54c0b03bf3443c3d931a367089']",NaN
30,orders,order_approved_at,訂單被核准時間(年月日時間),object,99441,160,0.001609,50462,"['2017/10/2 11:07', '2018/7/26 3:24', '2018/8/8 8:55']",NaN
31,orders,order_delivered_carrier_date,訂單交付給物流商的時間(年月日時間),object,99441,1783,0.017930,61544,"['2017/10/4 19:55', '2018/7/26 14:31', '2018/8/8 13:50']",NaN
32,orders,order_delivered_customer_date,訂單送達客戶地址時間(年月日時間),object,99441,2965,0.029817,75649,"['2017/10/10 21:25', '2018/8/7 15:27', '2018/8/17 18:06']",NaN
33,orders,order_estimated_delivery_date,訂單系統預估訂單送達時間(年月日時間),object,99441,0,0.000000,459,"['2017/10/18 0:00', '2018/8/13 0:00', '2018/9/4 0:00']",NaN
34,orders,order_id,訂單ID(PK),object,99441,0,0.000000,99441,"['e481f51cbdc54678b7cc49136f2d6af7', '53cdb2fc8bc7dce0b6741e2150273451', '47770eb9100c2d0c44946d9cf07ec65d']",NaN
35,orders,order_purchase_timestamp,客戶下單時間(年月日時間),object,99441,0,0.000000,88789,"['2017/10/2 10:56', '2018/7/24 20:41', '2018/8/8 8:38']",NaN
36,orders,order_status,訂單狀態(可區分成立/不成立),object,99441,0,0.000000,8,"['delivered', 'delivered', 'delivered']","['delivered', 'invoiced', 'shipped', 'processing', 'unavailable', 'canceled', 'created', 'approved']"
37,product,product_category_name,商品分類名稱(73種),object,32951,610,0.018512,73,"['perfumaria', 'artes', 'esporte_lazer']",NaN
38,product,product_description_lenght,商品描述長度,float64,32951,610,0.018512,2960,"[287.0, 276.0, 250.0]",NaN
39,product,product_height_cm,商品高度(cm),float64,32951,2,0.000061,102,"[10.0, 18.0, 9.0]",NaN
40,product,product_id,商品ID,object,32951,0,0.000000,32951,"['1e9e8ef04dbcff4541ed26657ea517e5', '3aa071139cb16b67ca9e5dea641aaa2f', '96bd76ec8810374ed1b65e291975717f']",NaN
41,product,product_length_cm,商品長度(cm),float64,32951,2,0.000061,99,"[16.0, 30.0, 18.0]",NaN
42,product,product_name_lenght,商品名稱長度(cm),float64,32951,610,0.018512,66,"[40.0, 44.0, 46.0]",NaN
43,product,product_photos_qty,商品照片數量1~20,float64,32951,610,0.018512,19,"[1.0, 1.0, 1.0]","[1.0, 4.0, 2.0, 3.0, 5.0, 9.0, 6.0, 7.0, 12.0, 10.0, 11.0, 17.0, 8.0, 15.0, 13.0, 14.0, 20.0, 18.0, 19.0]"
44,product,product_weight_g,商品重量(g),float64,32951,2,0.000061,2204,"[225.0, 1000.0, 154.0]",NaN
45,product,product_width_cm,商品寬度(cm),float64,32951,2,0.000061,95,"[14.0, 20.0, 15.0]",NaN
46,sellers,seller_city,賣家所在地(市),object,3095,0,0.000000,611,"['campinas', 'mogi guacu', 'rio de janeiro']",NaN
47,sellers,seller_id,賣家ID(PK),object,3095,0,0.000000,3095,"['3442f8959a84dea7ee197c632cb2df15', 'd1b65fc7debc3361ea86b5f14c68d2e2', 'ce3ad9de960102d0677a81f5d0bb7b2d']",NaN
48,sellers,seller_state,賣家所在地(州)用兩碼代碼表示,object,3095,0,0.000000,23,"['SP', 'SP', 'RJ']","['SP', 'RJ', 'PE', 'PR', 'GO', 'SC', 'BA', 'DF', 'RS', 'MG', 'RN', 'MT', 'CE', 'PB', 'AC', 'ES', 'RO', 'PI', 'MS', 'SE', 'MA', 'AM', 'PA']"
49,sellers,seller_zip_code_prefix,賣家郵遞區號前五碼，通常代表很細的地理區域,int64,3095,0,0.000000,2246,"[13023, 13844, 20031]",NaN
50,translation,product_category_name,翻譯表商品類別葡萄牙語(PK),object,71,0,0.000000,71,"['beleza_saude', 'informatica_acessorios', 'automotivo']",NaN
51,translation,product_category_name_english,翻譯表商品類別英文翻譯,object,71,0,0.000000,71,"['health_beauty', 'computers_accessories', 'auto']",NaN