In [4]:
import pandas as pd
import numpy as np

In [22]:


df = pd.DataFrame({
    "order_id": [
        "O001", "O002", "O003", "O004", "O005",
        "O006", "O007", "O008", "O009", None
    ],
    "customer_name": [
        "Alice", "Bob", "Carol", "David", "Emily",
        "Frank", None, "Helen", "Ian", "Jane"
    ],
    "age": [
        25, 32, None, 28, 40,
        None, 22, 35, 30, None
    ],
    "order_date": [
        "2024-03-01", "2024-03-02", "2024/03/05", "March 10, 2024", "2024-03-15",
        None, "2024-03-20", "2024/03/21", "2024-03-22", "March 25, 2024"
    ],
    "price": [
        "100", "150.5", None, "250.5", "300",
        "abc", "80", "120", None, "500"
    ],
    "status": [
        "Completed", "completed", "Completed", "CANCEL", "cancel",
        None, "Completed", "completed", "Completed", "CANCEL"
    ],
    "review": [
        None, "Good product", "Excellent", None, "Bad",
        "Okay", None, "Very good", "Excellent", None
    ]
})

df

  order_id customer_name   age      order_date  price     status        review
0     O001         Alice  25.0      2024-03-01    100  Completed          None
1     O002           Bob  32.0      2024-03-02  150.5  completed  Good product
2     O003         Carol   NaN      2024/03/05   None  Completed     Excellent
3     O004         David  28.0  March 10, 2024  250.5     CANCEL          None
4     O005         Emily  40.0      2024-03-15    300     cancel           Bad
5     O006         Frank   NaN            None    abc       None          Okay
6     O007          None  22.0      2024-03-20     80  Completed          None
7     O008         Helen  35.0      2024/03/21    120  completed     Very good
8     O009           Ian  30.0      2024-03-22   None  Completed     Excellent
9     None          Jane   NaN  March 25, 2024    500     CANCEL          None

In [23]:
df["review"].isna()

0     True
1    False
2    False
3     True
4    False
5    False
6     True
7    False
8    False
9     True
Name: review, dtype: bool

In [24]:
df["review"].isnull()

0     True
1    False
2    False
3     True
4    False
5    False
6     True
7    False
8    False
9     True
Name: review, dtype: bool

In [25]:
df["review"].fillna("我是補充值")

0           我是補充值
1    Good product
2       Excellent
3           我是補充值
4             Bad
5            Okay
6           我是補充值
7       Very good
8       Excellent
9           我是補充值
Name: review, dtype: object

In [26]:
df["age"].astype("object")

0    25.0
1    32.0
2     NaN
3    28.0
4    40.0
5     NaN
6    22.0
7    35.0
8    30.0
9     NaN
Name: age, dtype: object

In [27]:
df.loc[:,["age","review"]].fillna({"age":"未知年齡","review":"未知評價"})
# 針對某些欄位補充

    age        review
0  25.0          未知評價
1  32.0  Good product
2  未知年齡     Excellent
3  28.0          未知評價
4  40.0           Bad
5  未知年齡          Okay
6  22.0          未知評價
7  35.0     Very good
8  30.0     Excellent
9  未知年齡          未知評價

In [28]:
df["age"].astype("Int64")

0      25
1      32
2    <NA>
3      28
4      40
5    <NA>
6      22
7      35
8      30
9    <NA>
Name: age, dtype: Int64

In [29]:
df["age"].fillna(df["age"].median()) # 用中位數補空值

0    25.0
1    32.0
2    30.0
3    28.0
4    40.0
5    30.0
6    22.0
7    35.0
8    30.0
9    30.0
Name: age, dtype: float64

In [30]:
df["age"].fillna(df["age"].mean()) # 用平均數補充值

0    25.000000
1    32.000000
2    30.285714
3    28.000000
4    40.000000
5    30.285714
6    22.000000
7    35.000000
8    30.000000
9    30.285714
Name: age, dtype: float64

In [31]:
df["age"].fillna(method="ffill") # 用前一個有效值填充

/var/folders/vl/wskb2r0j55g_xcyvprs302bc0000gn/T/ipykernel_83508/2506526201.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["age"].fillna(method="ffill") # 用前一個有效值填充

0    25.0
1    32.0
2    32.0
3    28.0
4    40.0
5    40.0
6    22.0
7    35.0
8    30.0
9    30.0
Name: age, dtype: float64

In [32]:
df["age"].fillna(method="bfill") # 用後一個有效值填充

/var/folders/vl/wskb2r0j55g_xcyvprs302bc0000gn/T/ipykernel_83508/85016401.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["age"].fillna(method="bfill") # 用後一個有效值填充

0    25.0
1    32.0
2    28.0
3    28.0
4    40.0
5    22.0
6    22.0
7    35.0
8    30.0
9     NaN
Name: age, dtype: float64

In [33]:
df

  order_id customer_name   age      order_date  price     status        review
0     O001         Alice  25.0      2024-03-01    100  Completed          None
1     O002           Bob  32.0      2024-03-02  150.5  completed  Good product
2     O003         Carol   NaN      2024/03/05   None  Completed     Excellent
3     O004         David  28.0  March 10, 2024  250.5     CANCEL          None
4     O005         Emily  40.0      2024-03-15    300     cancel           Bad
5     O006         Frank   NaN            None    abc       None          Okay
6     O007          None  22.0      2024-03-20     80  Completed          None
7     O008         Helen  35.0      2024/03/21    120  completed     Very good
8     O009           Ian  30.0      2024-03-22   None  Completed     Excellent
9     None          Jane   NaN  March 25, 2024    500     CANCEL          None

In [34]:
df.dropna() # 默認axis=0 ， 有na row全部丟掉

  order_id customer_name   age  order_date  price     status        review
1     O002           Bob  32.0  2024-03-02  150.5  completed  Good product
4     O005         Emily  40.0  2024-03-15    300     cancel           Bad
7     O008         Helen  35.0  2024/03/21    120  completed     Very good

In [35]:
df.dropna(axis=1) # 刪掉有na 的 column

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
df.dropna(axis=0,how="any") # 默認any 有缺失就刪除

  order_id customer_name   age  order_date  price     status        review
1     O002           Bob  32.0  2024-03-02  150.5  completed  Good product
4     O005         Emily  40.0  2024-03-15    300     cancel           Bad
7     O008         Helen  35.0  2024/03/21    120  completed     Very good

In [38]:
df.dropna(axis=0,how="all") # 一個row的資料全部都是na才刪除

  order_id customer_name   age      order_date  price     status        review
0     O001         Alice  25.0      2024-03-01    100  Completed          None
1     O002           Bob  32.0      2024-03-02  150.5  completed  Good product
2     O003         Carol   NaN      2024/03/05   None  Completed     Excellent
3     O004         David  28.0  March 10, 2024  250.5     CANCEL          None
4     O005         Emily  40.0      2024-03-15    300     cancel           Bad
5     O006         Frank   NaN            None    abc       None          Okay
6     O007          None  22.0      2024-03-20     80  Completed          None
7     O008         Helen  35.0      2024/03/21    120  completed     Very good
8     O009           Ian  30.0      2024-03-22   None  Completed     Excellent
9     None          Jane   NaN  March 25, 2024    500     CANCEL          None

In [50]:
# 第 1 題：刪除任何欄位有缺失值的 row
df.dropna(axis=0)

  order_id customer_name   age  order_date  price     status        review
1     O002           Bob  32.0  2024-03-02  150.5  completed  Good product
4     O005         Emily  40.0  2024-03-15    300     cancel           Bad
7     O008         Helen  35.0  2024/03/21    120  completed     Very good

In [49]:
#第 2 題：刪除 order_id 缺失的 row（因為 order_id 是主鍵）
df.dropna(axis=0,subset=["order_id"])

  order_id customer_name   age      order_date  price     status        review
0     O001         Alice  25.0      2024-03-01    100  Completed          None
1     O002           Bob  32.0      2024-03-02  150.5  completed  Good product
2     O003         Carol   NaN      2024/03/05   None  Completed     Excellent
3     O004         David  28.0  March 10, 2024  250.5     CANCEL          None
4     O005         Emily  40.0      2024-03-15    300     cancel           Bad
5     O006         Frank   NaN            None    abc       None          Okay
6     O007          None  22.0      2024-03-20     80  Completed          None
7     O008         Helen  35.0      2024/03/21    120  completed     Very good
8     O009           Ian  30.0      2024-03-22   None  Completed     Excellent

In [54]:
#第 3 題：刪除缺失欄位超過 3 個的 row
df.dropna(axis=0,thresh=4) # 保留非缺失至少3個

  order_id customer_name   age      order_date  price     status        review
0     O001         Alice  25.0      2024-03-01    100  Completed          None
1     O002           Bob  32.0      2024-03-02  150.5  completed  Good product
2     O003         Carol   NaN      2024/03/05   None  Completed     Excellent
3     O004         David  28.0  March 10, 2024  250.5     CANCEL          None
4     O005         Emily  40.0      2024-03-15    300     cancel           Bad
5     O006         Frank   NaN            None    abc       None          Okay
6     O007          None  22.0      2024-03-20     80  Completed          None
7     O008         Helen  35.0      2024/03/21    120  completed     Very good
8     O009           Ian  30.0      2024-03-22   None  Completed     Excellent
9     None          Jane   NaN  March 25, 2024    500     CANCEL          None

In [56]:
#第 4 題：只刪除「全為缺失」的 row
df.dropna(axis=0,how="all")

  order_id customer_name   age      order_date  price     status        review
0     O001         Alice  25.0      2024-03-01    100  Completed          None
1     O002           Bob  32.0      2024-03-02  150.5  completed  Good product
2     O003         Carol   NaN      2024/03/05   None  Completed     Excellent
3     O004         David  28.0  March 10, 2024  250.5     CANCEL          None
4     O005         Emily  40.0      2024-03-15    300     cancel           Bad
5     O006         Frank   NaN            None    abc       None          Okay
6     O007          None  22.0      2024-03-20     80  Completed          None
7     O008         Helen  35.0      2024/03/21    120  completed     Very good
8     O009           Ian  30.0      2024-03-22   None  Completed     Excellent
9     None          Jane   NaN  March 25, 2024    500     CANCEL          None

In [57]:
#第 5 題：刪除有缺失的 columns
df.dropna(axis=1,how="any")

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [58]:
#第 6 題：保留「至少 5 個非缺失值」的 row (缺失三個就刪掉)
df.dropna(axis=0,thresh=5)

  order_id customer_name   age      order_date  price     status        review
0     O001         Alice  25.0      2024-03-01    100  Completed          None
1     O002           Bob  32.0      2024-03-02  150.5  completed  Good product
2     O003         Carol   NaN      2024/03/05   None  Completed     Excellent
3     O004         David  28.0  March 10, 2024  250.5     CANCEL          None
4     O005         Emily  40.0      2024-03-15    300     cancel           Bad
6     O007          None  22.0      2024-03-20     80  Completed          None
7     O008         Helen  35.0      2024/03/21    120  completed     Very good
8     O009           Ian  30.0      2024-03-22   None  Completed     Excellent

In [59]:
#第 7 題：刪除只有 review 缺失的 row（其他欄位不管）
df.dropna(axis=0,subset="review")

  order_id customer_name   age  order_date  price     status        review
1     O002           Bob  32.0  2024-03-02  150.5  completed  Good product
2     O003         Carol   NaN  2024/03/05   None  Completed     Excellent
4     O005         Emily  40.0  2024-03-15    300     cancel           Bad
5     O006         Frank   NaN        None    abc       None          Okay
7     O008         Helen  35.0  2024/03/21    120  completed     Very good
8     O009           Ian  30.0  2024-03-22   None  Completed     Excellent

In [63]:
#第 8 題：萃取出 age 有缺失的 row（不是 drop，是篩選）
df[df["age"].isna()]

  order_id customer_name  age      order_date price     status     review
2     O003         Carol  NaN      2024/03/05  None  Completed  Excellent
5     O006         Frank  NaN            None   abc       None       Okay
9     None          Jane  NaN  March 25, 2024   500     CANCEL       None

In [71]:
thresh = int(len(df) * 0.5)   # 至少要這麼多非缺失才保留
df_drop = df.dropna(axis=1, thresh=thresh)