In [2]:
import pandas as pd
import mysql.connector

In [4]:
# 模擬 order_item_dataset
order_item_dataset = pd.DataFrame({
    "order_item_id": [1, 2, 3],
    "purchase_date": [
        "2024-01-01 10:00:00",
        "2024-01-05 15:30:00",
        "2024-01-10 09:00:00",
    ]
})

# 模擬 payment_dataset
payment_dataset = pd.DataFrame({
    "payment_id": [101, 102, 103],
    "purchase_date": [
        "2024-01-02 12:00:00",
        "2024-01-06 18:45:00",
        "2024-01-08 08:20:00",
    ]
})

In [6]:
order_item_dataset["purchase_date"] = pd.to_datetime(order_item_dataset["purchase_date"])
payment_dataset["purchase_date"] = pd.to_datetime(payment_dataset["purchase_date"])

In [7]:
tables = {
    "order_item_dataset": order_item_dataset,
    "payment_dataset": payment_dataset
}
# 表名對應df

In [10]:
# 日期欄位字典
date_column = {
    "order_item_dataset":"purchase_date",
    "payment_dataset":"purchase_date"
}

In [11]:
def get_date_range_from_df(table_name, date_col):
    # 1. 根據 table_name 拿到對應的 DataFrame
    df = tables[table_name] # 利用key 抓的是talbes 字典的value，回傳的是字串值
    
    # 2. 取出這個欄位的最小 / 最大日期
    min_date = df[date_col].min()
    max_date = df[date_col].max()
    
    # 3. 組成一個只有一 row 的 DataFrame 回傳
    return pd.DataFrame({
        "min_date":   [min_date],
        "max_date":   [max_date],
        "table_name": [table_name],
        "date_column":[date_col]
    })

In [12]:
df_dates = pd.concat(
    [get_date_range_from_df(t, c) for t, c in date_column.items()],
    ignore_index=True
)

df_dates

             min_date            max_date          table_name    date_column
0 2024-01-01 10:00:00 2024-01-10 09:00:00  order_item_dataset  purchase_date
1 2024-01-02 12:00:00 2024-01-08 08:20:00     payment_dataset  purchase_date

In [ ]:
# 寫一個函數，接受參數table名字，日期欄位，回傳日期的最小與最大值
def get_date_range_from_df(table_name , col_name):
    df = tables[table_name]
    min_date = df[col_name].min()
    max_date = df[col_name].max()
    return pd.DataFrame(
    "min_date" : [min_date],
    "max_date" : [max_date],
    "table_name" : [table_name],
    "date_column" : [col_name]
    
    )

In [15]:
date_range_df = get_date_range_from_df("order_item_dataset" , "purchase_date")
date_range_df

             min_date            max_date          table_name    date_column
0 2024-01-01 10:00:00 2024-01-10 09:00:00  order_item_dataset  purchase_date

In [ ]:
df_dates = pd.concat(
    [get_date_range_from_df(t, c) for t, c in date_column.items()],
    ignore_index=True
)