In [3]:
import pandas as pd

In [5]:
ser = pd.Series([1,2,3,4,5])
ser

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
ser.dtypes

dtype('int64')

In [7]:
df = pd.DataFrame({
    "name": ["A", "B", "C"],
    "age": [20, 30, 40]
})

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes

In [9]:
df.describe()

        age
count   3.0
mean   30.0
std    10.0
min    20.0
25%    25.0
50%    30.0
75%    35.0
max    40.0

In [10]:
df.tail()

  name  age
0    A   20
1    B   30
2    C   40

In [11]:
df.sample()

  name  age
0    A   20

In [13]:
df.loc[:,"name"]

0    A
1    B
2    C
Name: name, dtype: object

In [17]:
print(df.loc[0,"age"])

20

In [18]:
df = pd.DataFrame({
    "name": ["A", "B", "C", "D", "E"],
    "age": [20, 30, 25, 40, 35],
    "gender": ["M", "F", "M", "F", "M"],
    "score": [88, 92, 75, 60, 95]
})

df

  name  age gender  score
0    A   20      M     88
1    B   30      F     92
2    C   25      M     75
3    D   40      F     60
4    E   35      M     95

In [19]:
#第 1 題：取 index = 2 的整列 row
df.loc[2]

name       C
age       25
gender     M
score     75
Name: 2, dtype: object

In [20]:
#第 2 題：取 index = 4 的 name 欄位值
df.loc[4,"name"]

'E'

In [22]:
#第 3 題：取 index = 0 到 2（含 2）的所有欄位
df.loc[0:2,:]

  name  age gender  score
0    A   20      M     88
1    B   30      F     92
2    C   25      M     75

In [23]:
# 第 4 題：取 index = 1 到 3 的 name 與 age 欄位
df.loc[1:3,["name","age"]]

  name  age
1    B   30
2    C   25
3    D   40

In [25]:
#第 5 題：用 .loc 取得所有男性（gender = "M"）的 row

df.loc[df["gender"]=="M",:]

  name  age gender  score
0    A   20      M     88
2    C   25      M     75
4    E   35      M     95

In [27]:
#第 6 題：取 index = 1 的 row 但只要 score 欄位
print(df.loc[1,"score"])

92

In [29]:
# 第 7 題：一次取兩個不連續的 row（index 0 和 3）
df.loc[[0,3],:]

  name  age gender  score
0    A   20      M     88
3    D   40      F     60

In [31]:
#第 8 題：取所有 row，但只要 columns = ["name", "score"]
df.loc[:,["name","score"]]

  name  score
0    A     88
1    B     92
2    C     75
3    D     60
4    E     95

In [32]:
#第 9 題（進階）：取 score >= 80 的所有人的 name 與 score

df.loc[df["score"]>=80,["name","score"]]

  name  score
0    A     88
1    B     92
4    E     95

In [33]:
#第 10 題（進階）：取 gender = F 的人，但只要 age 與 score

df.loc[df["gender"]=="F",["age","score"]]

   age  score
1   30     92
3   40     60

In [34]:
df = pd.DataFrame({
    "name": ["A", "B", "C", "D", "E"],
    "age": [20, 30, 25, 40, 35],
    "gender": ["M", "F", "M", "F", "M"],
    "score": [88, 92, 75, 60, 95]
})

df

  name  age gender  score
0    A   20      M     88
1    B   30      F     92
2    C   25      M     75
3    D   40      F     60
4    E   35      M     95

In [35]:
#第 1 題：取第 0 列（第一筆資料）

df.iloc[0]

name       A
age       20
gender     M
score     88
Name: 0, dtype: object

In [37]:
#第 2 題：取第 2 列（第三筆）的第 1 欄（age）
print(df.iloc[2,1])

25

In [38]:
#第 3 題：取第 1 到第 3 列（不含 3）
df.iloc[1:3]

  name  age gender  score
1    B   30      F     92
2    C   25      M     75

In [39]:
#第 4 題：取第 0 到第 2 列（含 2），但只取第 0 和第 3 欄（name、score）
df.iloc[0:3,[0,3]]

  name  score
0    A     88
1    B     92
2    C     75

In [41]:
#第 5 題：取第 4 列（最後一列）的最後一欄（score）
print(df.iloc[4,-1])

95

In [42]:
#第 6 題：一次取不連續 row（第 0、2、4 列）
df.iloc[[0,2,4]]

  name  age gender  score
0    A   20      M     88
2    C   25      M     75
4    E   35      M     95

In [43]:
#第 7 題：一次取不連續 columns（只取 age 與 score）
df.iloc[:,[1,3]]

   age  score
0   20     88
1   30     92
2   25     75
3   40     60
4   35     95

In [44]:
#第 8 題：取前三列（0,1,2）的所有欄位的所有值
df.iloc[[0,1,2]]

  name  age gender  score
0    A   20      M     88
1    B   30      F     92
2    C   25      M     75

In [45]:
#第 9 題：取第 1 到第 4 列（不含 4）與第 1 到第 3 欄（不含 3）

df.iloc[1:4,1:3]

   age gender
1   30      F
2   25      M
3   40      F

In [46]:
#第 10 題（進階）：取第 0、1、4 列，並且只取 name 與 score 兩欄

df.iloc[[0,1,4],[0,3]]

  name  score
0    A     88
1    B     92
4    E     95